### ISSUE TITLE
New Orleans Jambook

### ISSUE THREAD

**Issue by benschifman** [aspiers/book-indices#40]
This is really valuable, thanks. I couldn't figure out how to add it since i am new to github, but I made one for the New Orleans Jambook (http://cjam.lassecollin.se/). You can download it and add it if you wish at this [link](https://docs.google.com/spreadsheets/d/1p-WNnvke043d1gBH9gTPAuuvS9zdTk5ieWiQ8Y_dDJA/edit?usp=sharing).

**Comment by aspiers** [comment]
Super cool, thanks!  I used ChatGPT to separate out the titles which didn't have spaces or capitalization.

**Comment by benschifman** [comment]
Awesome -- appreciate it!
